apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-read
  template:
    metadata:
      labels:
        name: k8s-read
        app: k8s-read
    spec:
      serviceAccountName: kube-api-reader
      containers:
       - name: k8s-read
         image: cloudnativek8s/k8s-read:v2.0.0.2
         imagePullPolicy: IfNotPresent
         env:
         - name: CONTROLLER_NAME
           valueFrom:
             fieldRef:
               fieldPath: metadata.name
         - name: JOBS_NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
         - name: KUBERNETES_SERVICE_HOST
           value: "kubernetes.default.svc"
         - name: KUBERNETES_SERVICE_PORT
           value: "443"
         ports:
         - name: http
           containerPort: 6100
           protocol: TCP
         resources:
           requests:
             cpu: 50m
             memory: 128Mi
           limits:
             cpu: 50m
             memory: 128Mi

