kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gateway-read-role-binding
subjects:
  - kind: ServiceAccount
    name: kube-api-reader
    namespace: default
roleRef:
  kind: ClusterRole
  name: gateway-read-role
  apiGroup: rbac.authorization.k8s.io

